name: Deploy

on:
  repository_dispatch:
    types: [deploy]
env:
  ASTT_VERSION: 1.0.1
  
jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install SSH keys and connect
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
          ssh -i ~/.ssh/id_rsa ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }} "echo 'SSH connection successful'"
      
      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.ASTT_TEST_PASSWORD }}" | docker login ghcr.io --username "${{ secrets.ASTT_TEST_USERNAME }}" --password-stdin

      - name: Stop previous Docker containers
        ##run: docker compose down
        run: sudo systemctl stop astt-app.service
  
      - name: Remove old Docker images
        run: docker image prune -af
  
      - name: Pull Docker image
        run: docker pull ghcr.io/baloyixp/astt-cam-software-testing:latest
  
      - name: Start Docker containers
        #run: docker compose up -d
        run: sudo systemctl start astt-app.service

      - name: Reload Nginx configuration
        run: sudo systemctl reload nginx

      - name: Cleanup SSH keys
        run: rm -rf ~/.ssh
